[workspace]
resolver = "2"
members = ["bins/*", "crates/*", "e2e"]
default-members = ["crates/revm"]

[profile.release]
panic = "abort"
lto = true
opt-level = 'z'
strip = false
debug = false
debug-assertions = false
rpath = false
codegen-units = 1

[profile.ethtests]
inherits = "test"
opt-level = 3
