[workspace]
resolver = "2"
members = ["bins/*", "crates/*", "e2e"]
default-members = ["crates/revm"]

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 'z'
strip = true

[profile.ethtests]
inherits = "test"
opt-level = 3
