[package]
name = "revm-test"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.5"
hex = "0.4"
revm = { path = "../../crates/revm", version = "3.3.0", default-features=false }
microbench = "0.5"

[[bin]]
name = "analysis"

[[bin]]
name = "snailtracer"

[[bin]]
name = "transfer"
