[package]
authors = ["Dragan Rakita <dragan0rakita@gmail.com>"]
description = "REVM Primitives - Rust Primitives lib"
edition = "2021"
keywords = ["ethereum", "evm", "rust"]
license = "MIT"
name = "revm-primitives"
repository = "https://github.com/bluealloy/revm"
version = "0.2.0"

[dependencies]
bytes = { version = "1.1", default-features = false }
fixed-hash = { version = "0.8", default-features = false, features = [
    "rustc-hex",
] }
derive_more = "0.99"
ruint = { version = "1.7.0", features = ["primitive-types", "rlp"] }
serde = { version = "1.0", features = ["derive", "rc"], optional = true }
arbitrary = { version = "1.2", features = ["derive"], optional = true }

[dev-dependencies]
arbitrary = { version = "1.2", features = ["derive"]}

[features]
default = []
serde = ["dep:serde", "ruint/serde"]
arbitrary = ["dep:arbitrary", "ruint/arbitrary"]