[package]
name = "revm-e2e"
version = "0.1.0"
edition = "2021"

[dependencies]
revm-interpreter = { path = "../crates/interpreter", version = "1.3.0", default-features = false }
revm-precompile = { path = "../crates/precompile", version = "2.2.0", default-features = false }
revm = { path = "../crates/revm", version = "3.5.0", default-features = false, features = ["runtime"] }

# rwasm
fluentbase-codec = { git = "https://github.com/fluentlabs-xyz/fluentbase.git", branch = "devel", default-features = false }
fluentbase-sdk = { git = "https://github.com/fluentlabs-xyz/fluentbase.git", branch = "devel" }
fluentbase-types = { git = "https://github.com/fluentlabs-xyz/fluentbase.git", branch = "devel", default-features = false }

# rwasm runtime
fluentbase-runtime = { git = "https://github.com/fluentlabs-xyz/fluentbase.git", branch = "devel" }
fluentbase-rwasm = { git = "https://github.com/fluentlabs-xyz/fluentbase.git", branch = "devel" }

hex = "0.4.3"
hex-literal = "0.4.1"
wat = "1.0.83"
hashbrown = "0.14.3"
