[package]
edition = "2021"
name = "fork_ref_transact"
publish = false
version = "0.0.0"

[workspace]

[dependencies]
anyhow = "1.0.71"
tokio = {version = "1.28", features = [
  "rt-multi-thread",
  "macros",
]}

ethers-contract = {version = "2.0", default-features = false}
ethers-core = {version = "2.0"}
ethers-providers = {version = "2.0"}

# revm
revm = {git = "https://github.com/bluealloy/revm/", features = ["ethersdb"]}
revm-primitives = {git = "https://github.com/bluealloy/revm/"}
