[package]
authors = ["Dragan Rakita <dragan0rakita@gmail.com>"]
description = "Revm generic types wiring"
edition = "2021"
keywords = ["ethereum", "evm", "revm", "no_std"]
license = "MIT"
name = "revm-wiring"
repository = "https://github.com/bluealloy/revm"
version = "1.0.0"
readme = "../../README.md"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
unreachable_pub = "warn"
unused_must_use = "deny"
rust_2018_idioms = "deny"

[lints.rustdoc]
all = "warn"

[dependencies]
# revm
primitives.workspace = true
database-interface.workspace = true
specification.workspace = true
state.workspace = true

# mics
dyn-clone = "1.0"

# Optional
serde = { version = "1.0", default-features = false, features = [
    "derive",
    "rc",
], optional = true }


[dev-dependencies]

[features]
default = ["std"]
std = ["serde?/std"]
serde = ["dep:serde", "primitives/serde", "specification/serde", "state/serde"]
c-kzg = ["primitives/c-kzg"]
kzg-rs = ["primitives/kzg-rs"]
