name: Ethereum Tests

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  push:
    branches: [main, "release/**"]
  pull_request:
    branches: [main, "release/**"]

jobs:
  tests-stable:
    name: Ethereum Tests (Stable)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        profile: [ethtests, release]
        target: [i686-unknown-linux-gnu, x86_64-unknown-linux-gnu]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Checkout ethereum/tests
        uses: actions/checkout@v3
        with:
          repository: ethereum/tests
          path: ethtests
          submodules: recursive

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{matrix.target}}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: run
          args: --target ${{matrix.target}}
            --profile ${{ matrix.profile }} -p revme -- statetest
            ethtests/GeneralStateTests/
            ethtests/LegacyTests/Constantinople/GeneralStateTests/
            ethtests/EIPTests/StateTests/stEIP1153-transientStorage/
            ethtests/EIPTests/StateTests/stEIP4844-blobtransactions/
            ethtests/EIPTests/StateTests/stEIP5656-MCOPY/
